import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const db = new PrismaClient();

async function main() {
  // ── Admin user ──────────────────────────────────────────────────────────────
  const hash = await bcrypt.hash("admin123", 12);
  const admin = await db.user.upsert({
    where: { email: "admin@theteaplanet.com" },
    update: { role: "ADMIN", passwordHash: hash, name: "Admin" },
    create: { email: "admin@theteaplanet.com", name: "Admin", role: "ADMIN", passwordHash: hash },
  });
  console.log("Seeded admin:", admin.email, "role:", admin.role);

  // ── Product Knowledge Base ──────────────────────────────────────────────────
  const categories = [
    { name: "Beverage Premixes", description: "Ready-to-use bubble tea, milk tea, fruit tea and coffee premix powders — 40+ flavours", sortOrder: 1 },
    { name: "Tea Concentrates", description: "Premium liquid tea concentrates (Black, Green, Matcha, Mojito, Hojicha) — 30ml makes 150–200ml decoction", sortOrder: 2 },
    { name: "Syrups & Bases", description: "Brown sugar, caramel, fruit syrups and flavour bases for beverages — 15+ varieties", sortOrder: 3 },
    { name: "Popping Boba", description: "Fruit-juice filled popping pearls in 10+ flavours — mango, strawberry, lychee, passion fruit, blueberry and more", sortOrder: 4 },
    { name: "Tapioca Pearls", description: "Classic and specialty tapioca pearls — black, mini, flavoured, ready-to-cook and instant", sortOrder: 5 },
    { name: "Milkshake & Lassi Mixes", description: "Instant milkshake and lassi premix powders — 12+ flavours including cookies & cream, mango, butterscotch", sortOrder: 6 },
    { name: "Mocktail & Lemonade Mixes", description: "Ready-to-mix mocktail and lemonade concentrates — 15+ trendy flavours for bars, cafes and events", sortOrder: 7 },
    { name: "Boba Desserts", description: "Taro jar cakes, matcha Swiss rolls, dessert cups and boba-inspired sweets — 19+ products", sortOrder: 8 },
    { name: "Industrial Ingredients", description: "Bulk 20kg packs of Popping Boba, Konjac Pearls, Nata de Coco, Tapioca Pearls for large-scale operators", sortOrder: 9 },
  ];

  for (const cat of categories) {
    await db.productCategory.upsert({
      where: { name: cat.name },
      update: { description: cat.description, sortOrder: cat.sortOrder },
      create: cat,
    });
  }

  const premixCat     = await db.productCategory.findUnique({ where: { name: "Beverage Premixes" } });
  const concCat       = await db.productCategory.findUnique({ where: { name: "Tea Concentrates" } });
  const syrupCat      = await db.productCategory.findUnique({ where: { name: "Syrups & Bases" } });
  const poppingCat    = await db.productCategory.findUnique({ where: { name: "Popping Boba" } });
  const tapiocaCat    = await db.productCategory.findUnique({ where: { name: "Tapioca Pearls" } });
  const milkshakeCat  = await db.productCategory.findUnique({ where: { name: "Milkshake & Lassi Mixes" } });
  const mocktailCat   = await db.productCategory.findUnique({ where: { name: "Mocktail & Lemonade Mixes" } });
  const dessertCat    = await db.productCategory.findUnique({ where: { name: "Boba Desserts" } });
  const industrialCat = await db.productCategory.findUnique({ where: { name: "Industrial Ingredients" } });

  const products = [
    // ── Beverage Premixes ──────────────────────────────────────────────────────
    {
      sku: "BP-TARO-500",
      name: "Taro Bubble Tea Premix",
      categoryId: premixCat!.id,
      description: "Classic taro-flavoured bubble tea premix powder. Just add water — no blender or espresso machine needed. 20 servings per 500g pouch.",
      targetCustomers: "cafes, bubble tea shops, QSR chains, food courts, hotels, cloud kitchens, college canteens",
      usages: "Hot/iced bubble tea, milky taro drinks, smoothie base, café menu extension",
      keyBenefits: "No special equipment needed, consistent taste every batch, 200%+ gross margin per cup, long shelf life, easy staff training",
      hsnCode: "2101",
      gstRate: 18,
      mrp: 450,
      dealerPrice: 320,
      moq: "1 pouch (500g)",
      packSize: "500g pouch (approx. 20 servings)",
      shelfLife: "12 months",
      sortOrder: 1,
    },
    {
      sku: "BP-MANGO-500",
      name: "Mango Bubble Tea Premix",
      categoryId: premixCat!.id,
      description: "Tropical mango flavoured boba premix — a bestseller for summer menus. Natural mango flavour, no artificial colours.",
      targetCustomers: "cafes, bubble tea shops, QSR chains, hotels, resorts, juice bars, cloud kitchens",
      usages: "Bubble tea, iced mango tea, mango slushie base, party drinks, fruit tea",
      keyBenefits: "Natural mango flavour, no artificial colours, fast preparation under 2 minutes, high seasonal demand, top-selling SKU",
      hsnCode: "2101",
      gstRate: 18,
      mrp: 450,
      dealerPrice: 320,
      moq: "1 pouch (500g)",
      packSize: "500g pouch (approx. 20 servings)",
      shelfLife: "12 months",
      sortOrder: 2,
    },
    {
      sku: "BP-MATCHA-500",
      name: "Matcha Bubble Tea Premix",
      categoryId: premixCat!.id,
      description: "Japanese-style matcha green tea bubble tea premix. Growing demand among health-conscious millennials and Gen Z consumers.",
      targetCustomers: "specialty cafes, health cafes, yoga studios, wellness centres, premium hotels, beverage startups",
      usages: "Hot/cold matcha latte, matcha boba, matcha smoothie, matcha frappe",
      keyBenefits: "Authentic matcha flavour, health positioning, premium pricing potential, top trending SKU 2024–25",
      hsnCode: "2101",
      gstRate: 18,
      mrp: 520,
      dealerPrice: 370,
      moq: "1 pouch (500g)",
      packSize: "500g pouch (approx. 20 servings)",
      shelfLife: "12 months",
      sortOrder: 3,
    },
    {
      sku: "BP-STRAWBERRY-500",
      name: "Strawberry Bubble Tea Premix",
      categoryId: premixCat!.id,
      description: "Sweet strawberry boba premix — popular with younger audiences and dessert-focused cafes. Appealing pink colour.",
      targetCustomers: "dessert cafes, bakeries, ice cream parlours, bubble tea shops, college canteens, events",
      usages: "Boba drinks, strawberry iced tea, dessert drinks, smoothie base, event beverages",
      keyBenefits: "Appealing pink colour, popular with Gen Z, easy cross-sell with desserts, consistent colour every serve",
      hsnCode: "2101",
      gstRate: 18,
      mrp: 450,
      dealerPrice: 320,
      moq: "1 pouch (500g)",
      packSize: "500g pouch (approx. 20 servings)",
      shelfLife: "12 months",
      sortOrder: 4,
    },
    {
      sku: "BP-CHOCOLATE-500",
      name: "Chocolate Bubble Tea Premix",
      categoryId: premixCat!.id,
      description: "Rich chocolate boba premix — combines the chocolate shake experience with bubble tea format. Works hot and cold.",
      targetCustomers: "cafes, dessert parlours, QSR chains, college canteens, multiplexes, cloud kitchens",
      usages: "Chocolate boba, hot chocolate boba, choco shake, dessert drink, mocha tea",
      keyBenefits: "Universal appeal across age groups, works hot and cold, high repeat purchase rate, easy upsell item",
      hsnCode: "2101",
      gstRate: 18,
      mrp: 480,
      dealerPrice: 340,
      moq: "1 pouch (500g)",
      packSize: "500g pouch (approx. 20 servings)",
      shelfLife: "12 months",
      sortOrder: 5,
    },
    {
      sku: "BP-THAI-ORANGE-500",
      name: "Thai Orange Tea Premix",
      categoryId: premixCat!.id,
      description: "Authentic Thai-style orange milk tea premix — the iconic orange-hued street drink beloved across Southeast Asia.",
      targetCustomers: "Thai restaurants, Asian fusion cafes, bubble tea shops, QSR chains, food courts",
      usages: "Thai iced tea, hot Thai milk tea, layered bubble tea, party drinks",
      keyBenefits: "Iconic orange colour for visual appeal, trending South-East Asian flavour, premium menu positioning",
      hsnCode: "2101",
      gstRate: 18,
      mrp: 460,
      dealerPrice: 330,
      moq: "1 pouch (500g)",
      packSize: "500g pouch",
      shelfLife: "12 months",
      sortOrder: 6,
    },
    {
      sku: "BP-MASALA-CHAI-1KG",
      name: "Masala Chai Premix",
      categoryId: premixCat!.id,
      description: "Traditional Indian masala chai premix with real spices — cardamom, ginger, cinnamon. Ideal for vending machines and bulk institutional use.",
      targetCustomers: "office canteens, hotels, dhabas, airports, hospital cafeterias, corporate offices, railways",
      usages: "Vending machines, bulk institutional chai, takeaway chai stalls, hospitality sector, corporate pantries",
      keyBenefits: "Authentic taste with real spices, consistent quality every cup, no brewing required, FSSAI certified, very high volume SKU",
      hsnCode: "2101",
      gstRate: 18,
      mrp: 380,
      dealerPrice: 260,
      moq: "1 kg pouch",
      packSize: "1 kg (approx. 100 cups)",
      shelfLife: "18 months",
      sortOrder: 7,
    },
    {
      sku: "BP-CAPPUCCINO-1KG",
      name: "Cappuccino Coffee Premix",
      categoryId: premixCat!.id,
      description: "Rich and frothy cappuccino premix — barista-quality coffee in seconds. No espresso machine needed.",
      targetCustomers: "offices, hotels, cafes, vending operators, co-working spaces, IT parks, corporate offices",
      usages: "Hot cappuccino, iced cappuccino, frothy drinks, vending machines, office pantries",
      keyBenefits: "Consistent barista taste without equipment, great vending machine ROI, FSSAI approved, high-margin café item",
      hsnCode: "2101",
      gstRate: 18,
      mrp: 560,
      dealerPrice: 390,
      moq: "1 kg pouch",
      packSize: "1 kg (approx. 80 cups)",
      shelfLife: "18 months",
      sortOrder: 8,
    },
    // ── Tea Concentrates ───────────────────────────────────────────────────────
    {
      sku: "TC-BLACK-1L",
      name: "Black Tea Concentrate",
      categoryId: concCat!.id,
      description: "Premium black tea liquid concentrate — 30ml makes 150–200ml full-strength tea decoction. Direct sourced from Assam and West Bengal.",
      targetCustomers: "cafes, bubble tea shops, restaurants, hotels, QSR chains, cloud kitchens, caterers",
      usages: "Bubble tea base, iced tea, hot tea decoction, milk tea, chai base, masala tea",
      keyBenefits: "Direct farm sourcing from Assam & West Bengal, 1 bottle replaces 100+ tea bags, premium taste consistency, HALAL certified",
      hsnCode: "2101",
      gstRate: 18,
      mrp: 350,
      dealerPrice: 240,
      moq: "1 bottle (1L)",
      packSize: "1L bottle (33+ servings at 30ml per serve)",
      shelfLife: "18 months",
      sortOrder: 1,
    },
    {
      sku: "TC-MATCHA-500ML",
      name: "Matcha Green Tea Concentrate",
      categoryId: concCat!.id,
      description: "Premium matcha concentrate sourced from Japan-grade tea farms. Rich umami flavour for premium beverage applications.",
      targetCustomers: "specialty cafes, health cafes, premium hotels, wellness centres, beverage startups",
      usages: "Matcha latte, matcha boba, matcha smoothie, matcha frappe, dessert applications",
      keyBenefits: "Japan-grade matcha quality, health positioning, premium pricing potential, trending product 2024–25",
      hsnCode: "0902",
      gstRate: 5,
      mrp: 480,
      dealerPrice: 340,
      moq: "1 bottle (500ml)",
      packSize: "500ml bottle",
      shelfLife: "12 months",
      sortOrder: 3,
    },
    // ── Syrups & Bases ─────────────────────────────────────────────────────────
    {
      sku: "SB-BROWN-SUGAR-750ML",
      name: "Brown Sugar Syrup",
      categoryId: syrupCat!.id,
      description: "Authentic Taiwanese brown sugar syrup for tiger milk tea and brown sugar boba drinks. Deep caramel-molasses flavour.",
      targetCustomers: "bubble tea shops, cafes, QSR chains, dessert parlours, cloud kitchens",
      usages: "Tiger milk tea, brown sugar boba, pancake drizzle, dessert topping, iced drinks",
      keyBenefits: "Authentic Taiwanese flavour profile, dramatic tiger-stripe visual for Instagram content, consistent colour and taste",
      hsnCode: "1702",
      gstRate: 18,
      mrp: 280,
      dealerPrice: 190,
      moq: "1 bottle (750ml)",
      packSize: "750ml bottle",
      shelfLife: "18 months",
      sortOrder: 1,
    },
    {
      sku: "SB-LYCHEE-750ML",
      name: "Lychee Syrup",
      categoryId: syrupCat!.id,
      description: "Premium lychee flavour syrup for mocktails, bubble tea, and fruit drinks. Versatile base for multiple drink applications.",
      targetCustomers: "cocktail/mocktail bars, cafes, restaurants, hotels, bubble tea shops, event caterers",
      usages: "Mocktails, lychee iced tea, bubble tea flavouring, dessert topping, lemonade mixer",
      keyBenefits: "Versatile — works across 5+ drink types, premium floral taste, low cost per serve, FSSAI approved",
      hsnCode: "2106",
      gstRate: 18,
      mrp: 320,
      dealerPrice: 220,
      moq: "1 bottle (750ml)",
      packSize: "750ml bottle",
      shelfLife: "24 months",
      sortOrder: 2,
    },
    {
      sku: "SB-PASSION-750ML",
      name: "Passion Fruit Syrup",
      categoryId: syrupCat!.id,
      description: "Tangy passion fruit syrup — trending tropical flavour for cafes and bars. Vibrant yellow colour for visual appeal.",
      targetCustomers: "cafes, bars, restaurants, beach resorts, juice bars, event caterers, cloud kitchens",
      usages: "Mocktails, passion fruit iced tea, tropical drinks, cocktail mixers, fruit bubble tea",
      keyBenefits: "Trending tropical flavour, Instagram-worthy yellow colour, high-margin drinks, fast-growing category",
      hsnCode: "2106",
      gstRate: 18,
      mrp: 340,
      dealerPrice: 230,
      moq: "1 bottle (750ml)",
      packSize: "750ml bottle",
      shelfLife: "24 months",
      sortOrder: 3,
    },
    // ── Popping Boba ───────────────────────────────────────────────────────────
    {
      sku: "PB-MANGO-450G",
      name: "Mango Popping Boba",
      categoryId: poppingCat!.id,
      description: "Mango juice-filled popping pearls that burst in the mouth. The #1 topping for bubble tea and desserts.",
      targetCustomers: "bubble tea shops, cafes, dessert parlours, QSR chains, hotels, ice cream shops",
      usages: "Bubble tea topping, yogurt topping, dessert cup, ice cream sundae, pancake topping",
      keyBenefits: "Burst-on-bite experience drives repeat orders, vibrant colour for visual appeal, ready to use (no cooking), 200%+ margin",
      hsnCode: "2106",
      gstRate: 18,
      mrp: 380,
      dealerPrice: 260,
      moq: "1 jar (450g)",
      packSize: "450g jar (approx. 30 servings)",
      shelfLife: "12 months",
      sortOrder: 1,
    },
    {
      sku: "PB-STRAWBERRY-450G",
      name: "Strawberry Popping Boba",
      categoryId: poppingCat!.id,
      description: "Strawberry juice-filled popping pearls with a vivid red colour. Top-selling popping boba among young customers.",
      targetCustomers: "bubble tea shops, dessert cafes, ice cream shops, QSR chains, birthday venues",
      usages: "Bubble tea, dessert topping, frozen yogurt, smoothie bowl, cake decoration",
      keyBenefits: "Vivid red colour for visual impact, popular with children and Gen Z, ready to use — no cooking needed",
      hsnCode: "2106",
      gstRate: 18,
      mrp: 380,
      dealerPrice: 260,
      moq: "1 jar (450g)",
      packSize: "450g jar",
      shelfLife: "12 months",
      sortOrder: 2,
    },
    {
      sku: "PB-LYCHEE-450G",
      name: "Lychee Popping Boba",
      categoryId: poppingCat!.id,
      description: "Delicate lychee juice-filled pearls — floral, light and refreshing. Pairs perfectly with green and white teas.",
      targetCustomers: "premium cafes, bubble tea shops, hotels, wellness cafes, Asian restaurants",
      usages: "Premium bubble tea, mocktail garnish, dessert cup, yogurt bowl, fruit salad",
      keyBenefits: "Premium floral flavour profile, pairs with 10+ tea bases, unique differentiation for menus",
      hsnCode: "2106",
      gstRate: 18,
      mrp: 400,
      dealerPrice: 275,
      moq: "1 jar (450g)",
      packSize: "450g jar",
      shelfLife: "12 months",
      sortOrder: 3,
    },
    // ── Tapioca Pearls ─────────────────────────────────────────────────────────
    {
      sku: "TP-BLACK-1KG",
      name: "Classic Black Tapioca Pearls",
      categoryId: tapiocaCat!.id,
      description: "Traditional black tapioca boba pearls — the original bubble tea experience. Cook in 30 minutes, serve for up to 4 hours.",
      targetCustomers: "bubble tea shops, cafes, QSR chains, restaurants, cloud kitchens, caterers",
      usages: "Classic bubble tea, milk tea, dessert cups, taro pudding, tapioca drinks",
      keyBenefits: "The foundational boba ingredient, 1 kg = 80–100 servings, consistent chewy texture, long cook window",
      hsnCode: "1903",
      gstRate: 18,
      mrp: 320,
      dealerPrice: 210,
      moq: "1 kg pouch",
      packSize: "1 kg (80–100 servings)",
      shelfLife: "24 months",
      sortOrder: 1,
    },
    {
      sku: "TP-INSTANT-1KG",
      name: "Instant Tapioca Pearls",
      categoryId: tapiocaCat!.id,
      description: "Quick-cook tapioca pearls ready in just 5 minutes — perfect for high-volume and fast-service operations.",
      targetCustomers: "QSR chains, food courts, cloud kitchens, caterers, events, college canteens",
      usages: "Fast bubble tea service, takeaway shops, food court counters, event beverage stalls",
      keyBenefits: "Ready in 5 minutes vs 30 minutes standard, reduces prep time 80%, ideal for high-volume service, consistent texture",
      hsnCode: "1903",
      gstRate: 18,
      mrp: 380,
      dealerPrice: 260,
      moq: "1 kg pouch",
      packSize: "1 kg",
      shelfLife: "24 months",
      sortOrder: 2,
    },
    // ── Milkshake & Lassi Mixes ────────────────────────────────────────────────
    {
      sku: "ML-MANGO-LASSI-500",
      name: "Mango Lassi Mix",
      categoryId: milkshakeCat!.id,
      description: "Premium mango lassi premix powder — authentic Indian taste in seconds. Just blend with curd or milk.",
      targetCustomers: "Indian restaurants, dhabas, hotels, juice bars, canteens, cloud kitchens, caterers",
      usages: "Mango lassi, mango smoothie, mango milkshake, festive menus, takeaway drinks",
      keyBenefits: "Authentic mango taste, fast preparation, no fruit blending needed, high festive demand (weddings, Diwali, Eid)",
      hsnCode: "2106",
      gstRate: 18,
      mrp: 380,
      dealerPrice: 260,
      moq: "1 pouch (500g)",
      packSize: "500g pouch (approx. 15 servings)",
      shelfLife: "12 months",
      sortOrder: 1,
    },
    {
      sku: "ML-COOKIES-CREAM-500",
      name: "Cookies & Cream Milkshake Mix",
      categoryId: milkshakeCat!.id,
      description: "Indulgent cookies and cream milkshake premix — a café favourite for millennials and dessert lovers.",
      targetCustomers: "cafes, dessert parlours, ice cream shops, QSR chains, multiplexes, college canteens",
      usages: "Thick milkshake, dessert drink, frappé base, boba milkshake, birthday celebration drink",
      keyBenefits: "Café-quality shake without ice cream machine, millennial favourite, high margin dessert drink, premium visual appeal",
      hsnCode: "2106",
      gstRate: 18,
      mrp: 420,
      dealerPrice: 290,
      moq: "1 pouch (500g)",
      packSize: "500g pouch",
      shelfLife: "12 months",
      sortOrder: 2,
    },
    {
      sku: "ML-BUTTERSCOTCH-500",
      name: "Butterscotch Milkshake Mix",
      categoryId: milkshakeCat!.id,
      description: "Classic butterscotch milkshake premix — the perennial crowd-pleaser across all age groups.",
      targetCustomers: "cafes, restaurants, QSR chains, ice cream shops, canteens, cloud kitchens",
      usages: "Butterscotch milkshake, butterscotch frappe, dessert base, birthday party drinks",
      keyBenefits: "Universal appeal, top-10 milkshake flavour nationwide, high repeat purchase, easy cross-sell with desserts",
      hsnCode: "2106",
      gstRate: 18,
      mrp: 380,
      dealerPrice: 260,
      moq: "1 pouch (500g)",
      packSize: "500g pouch",
      shelfLife: "12 months",
      sortOrder: 3,
    },
    // ── Mocktail & Lemonade Mixes ──────────────────────────────────────────────
    {
      sku: "MM-VIRGIN-MOJITO-750ML",
      name: "Virgin Mojito Mix",
      categoryId: mocktailCat!.id,
      description: "Ready-to-mix virgin mojito concentrate with real mint and lime flavour. The most-ordered mocktail in India.",
      targetCustomers: "restaurants, cafes, bars, hotels, resorts, event caterers, cloud kitchens, wedding venues",
      usages: "Virgin mojito, sparkling lemonade, mocktail pitcher, event drinks, party beverages",
      keyBenefits: "#1 selling mocktail flavour, real mint-lime taste, fast service (no muddling), consistent taste every glass",
      hsnCode: "2106",
      gstRate: 18,
      mrp: 300,
      dealerPrice: 200,
      moq: "1 bottle (750ml)",
      packSize: "750ml bottle (25–30 servings at 25ml dilution)",
      shelfLife: "18 months",
      sortOrder: 1,
    },
    {
      sku: "MM-WATERMELON-LIME-750ML",
      name: "Watermelon Lemonade Mix",
      categoryId: mocktailCat!.id,
      description: "Vibrant watermelon lemonade concentrate — a refreshing summer bestseller with eye-catching pink colour.",
      targetCustomers: "cafes, juice bars, restaurants, resorts, beach clubs, food festivals, cloud kitchens",
      usages: "Watermelon lemonade, sparkling watermelon soda, pink mocktail, summer menu feature",
      keyBenefits: "Striking pink colour drives Instagram sharing, summer bestseller, high single-serve margin, zero prep required",
      hsnCode: "2106",
      gstRate: 18,
      mrp: 280,
      dealerPrice: 190,
      moq: "1 bottle (750ml)",
      packSize: "750ml bottle",
      shelfLife: "18 months",
      sortOrder: 2,
    },
    // ── Boba Desserts ──────────────────────────────────────────────────────────
    {
      sku: "BD-TARO-JAR-CAKE",
      name: "Taro Jar Cake Mix",
      categoryId: dessertCat!.id,
      description: "Taro-flavoured jar cake premix — easy to assemble, stunning to present, premium pricing potential for cafes.",
      targetCustomers: "dessert cafes, bakeries, cloud kitchens, restaurants, hotels, caterers, gifting businesses",
      usages: "Individual dessert jars, takeaway desserts, corporate gifting, café dessert menu, online delivery",
      keyBenefits: "No oven needed, Instagram-worthy presentation, high margin dessert item, café menu differentiator",
      hsnCode: "1901",
      gstRate: 18,
      mrp: 320,
      dealerPrice: 210,
      moq: "1 pack (makes 10 jars)",
      packSize: "Pack for 10 servings",
      shelfLife: "6 months",
      sortOrder: 1,
    },
    {
      sku: "BD-MATCHA-SWISS-ROLL",
      name: "Matcha Swiss Roll Mix",
      categoryId: dessertCat!.id,
      description: "Matcha-flavoured Swiss roll premix — premium Japanese-inspired dessert for high-end cafe and bakery menus.",
      targetCustomers: "bakeries, dessert cafes, specialty cafes, hotels, cloud kitchens, patisseries",
      usages: "Swiss roll cakes, dessert platters, afternoon tea menus, premium takeaway items",
      keyBenefits: "Japanese flavour trend, premium aesthetic, differentiation for bakeries, pairs with matcha beverage menu",
      hsnCode: "1901",
      gstRate: 18,
      mrp: 380,
      dealerPrice: 260,
      moq: "1 pack",
      packSize: "Pack for 8–10 servings",
      shelfLife: "6 months",
      sortOrder: 2,
    },
    // ── Industrial Ingredients ─────────────────────────────────────────────────
    {
      sku: "IND-POPPING-BOBA-20KG",
      name: "Popping Boba — Industrial 20kg Bucket",
      categoryId: industrialCat!.id,
      description: "Bulk popping boba in 20kg buckets for large-scale operations. Available in mango, strawberry, lychee, passion fruit and blueberry.",
      targetCustomers: "large QSR chains, hotel groups, food manufacturers, distributors, large-scale caterers",
      usages: "High-volume bubble tea production, dessert manufacturing, food service chains, co-packing",
      keyBenefits: "60–70% lower per-kg cost vs retail pack, industrial-grade quality, FSSC 22000 certified, HALAL certified",
      hsnCode: "2106",
      gstRate: 18,
      mrp: null,
      dealerPrice: null,
      moq: "1 bucket (20kg) — call for pricing",
      packSize: "20kg food-grade bucket",
      shelfLife: "12 months",
      sortOrder: 1,
    },
    {
      sku: "IND-TAPIOCA-PEARLS-20KG",
      name: "Tapioca Pearls — Industrial 20kg Pack",
      categoryId: industrialCat!.id,
      description: "Bulk tapioca pearls for large bubble tea chains and food manufacturers. Consistent size and cook time for high-volume production.",
      targetCustomers: "QSR chains, hotel groups, food manufacturers, large distributors, cloud kitchen brands",
      usages: "Chain-level bubble tea production, central kitchen supply, food manufacturing",
      keyBenefits: "Consistent pearl size and cook time, bulk pricing advantage, FSSAI certified, direct manufacturer pricing",
      hsnCode: "1903",
      gstRate: 18,
      mrp: null,
      dealerPrice: null,
      moq: "1 pack (20kg) — call for pricing",
      packSize: "20kg pack",
      shelfLife: "24 months",
      sortOrder: 2,
    },
  ];

  for (const product of products) {
    await db.product.upsert({
      where: { sku: product.sku },
      update: {
        name: product.name,
        categoryId: product.categoryId,
        description: product.description,
        targetCustomers: product.targetCustomers,
        usages: product.usages,
        keyBenefits: product.keyBenefits,
        hsnCode: product.hsnCode,
        gstRate: product.gstRate,
        mrp: product.mrp,
        dealerPrice: product.dealerPrice,
        moq: product.moq,
        packSize: product.packSize,
        shelfLife: product.shelfLife,
        sortOrder: product.sortOrder,
      },
      create: product,
    });
  }

  console.log(`Seeded ${products.length} products across ${categories.length} categories`);
}

main()
  .catch(console.error)
  .finally(() => db.$disconnect());
